=== almerindo/TTAir_IMPL/conf/TTAirBehaviorSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    vc:maxVersion="1.1" vc:minVersion="1.0" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning">
    <xs:complexType name="TTAirBasicType">
    	<xs:sequence>
    		<xs:element name="Name" type="xs:normalizedString" minOccurs="0" maxOccurs="1"/>
    		<xs:element minOccurs="0" name="Description"
    			type="xs:string" />
    	</xs:sequence>
    	<xs:attribute name="ID" type="xs:ID" use="required"/>
    </xs:complexType>
    <xs:complexType name="TTAirActionType">
    	<xs:complexContent>
    		<xs:extension base="TTAirBasicType">
    			<xs:attribute name="ClassName" type="xs:string" use="required"></xs:attribute>
    		</xs:extension>
    	</xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TTAirInteractionType">
    	<xs:complexContent>
    		<xs:extension base="TTAirBasicType">
    			<xs:attribute name="ClassName" type="xs:string" use="required"></xs:attribute>
    		</xs:extension>
    	</xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TTAirBehaviorFrameType">
        <xs:complexContent>
            <xs:extension base="TTAirBasicType">
                <xs:sequence>
                	<xs:element name="Event" type="TTAirEventType" minOccurs="1" maxOccurs="1"></xs:element>
                	<xs:element minOccurs="1" name="ActionID"
                		type="xs:IDREFS" maxOccurs="unbounded"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TTAirExpectancyType">
        <xs:complexContent>
            <xs:extension base="TTAirBasicType">
                <xs:sequence>
                    <xs:element form="qualified" name="BehaviorframeID" type="xs:IDREFS" maxOccurs="unbounded" minOccurs="0"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TTAirBehaviorChainType">
        <xs:complexContent>
            <xs:extension base="TTAirBasicType">
                <xs:sequence>
                	<xs:element name="ExpectancyID" type="xs:IDREFS" maxOccurs="unbounded" minOccurs="1"/>
                	<xs:element name="ExpectancyTransition" type="TTAirExpectancyTransition" maxOccurs="unbounded" minOccurs="0"></xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TTAirExpectancyTransition">
    	<xs:sequence>
    		<xs:element name="CausedBy" type="xs:IDREF" minOccurs="1" maxOccurs="unbounded">
    			<xs:annotation>
    				<xs:documentation>BehaviorFrame que irá causar a transição.</xs:documentation>
    			</xs:annotation></xs:element>
    	</xs:sequence>
    	<xs:attribute name="ID" type="xs:ID" use="required"/>
    	<xs:attribute name="Source" type="xs:IDREF" use="required" >
    		<xs:annotation>
    			<xs:documentation>ID da Expectancy Origem</xs:documentation>
    		</xs:annotation></xs:attribute>
    	<xs:attribute name="Target" type="xs:IDREF" use="required" >
    		<xs:annotation>
    			<xs:documentation>ID da Expectancy destino</xs:documentation>
    		</xs:annotation></xs:attribute>
    </xs:complexType>
    <xs:group name="interactionList">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" minOccurs="1" name="Interaction"
                type="TTAirInteractionType"/>
        </xs:sequence>
    </xs:group>
    <xs:group name="actionList">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" minOccurs="1" name="Action" type="TTAirActionType"/>
        </xs:sequence>
    </xs:group>
    <xs:group name="behaviorFrameList">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" minOccurs="1" name="BehaviorFrame"
                type="TTAirBehaviorFrameType"/>
        </xs:sequence>
    </xs:group>
    <xs:group name="expectancyList">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" minOccurs="1" name="Expectancy"
                type="TTAirExpectancyType"/>
        </xs:sequence>
    </xs:group>
    <xs:group name="expectancyTransitionList">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="expectancyTransition"
                type="TTAirExpectancyTransition"/>
        </xs:sequence>
    </xs:group>
    <xs:element name="Behavior">
        <xs:complexType>
        	<xs:sequence>
        		<xs:group ref="interactionList" />
        		<xs:group ref="actionList" />
        		<xs:group ref="behaviorFrameList" />
        		<xs:group ref="expectancyList" />
        		<xs:element name="BehaviorChain" maxOccurs="unbounded"
        			minOccurs="1">
        			<xs:complexType>
        				<xs:complexContent>
        					<xs:extension
        						base="TTAirBehaviorChainType">
        						<xs:group
        							ref="expectancyTransitionList" />
        					</xs:extension>
        				</xs:complexContent>
        			</xs:complexType>
        		</xs:element>
        	</xs:sequence>
        	<xs:attribute name="Log" type="xs:boolean" use="required"
        		default="true">
        	</xs:attribute>
        	<xs:attribute name="FilePathLog" type="xs:string"
        		default="./BehaviorLog.log">
        	</xs:attribute>
        	<xs:attribute name="ID" type="xs:ID" use="required"></xs:attribute>
        </xs:complexType>
    </xs:element>


    <xs:complexType name="TTAirEventType">
    	<xs:complexContent>
    		<xs:extension base="TTAirBasicType">

    			<xs:attribute name="RecognizerID" type="xs:IDREF"
    				use="required">
    			</xs:attribute>

    			<xs:attribute name="Cod" type="xs:string"
    				use="required">
    				<xs:annotation>
    					<xs:documentation>
    						Cod é o código do evento que será enviado ou
    						recebido.
    					</xs:documentation>
    				</xs:annotation>
    			</xs:attribute>

    		</xs:extension>
    	</xs:complexContent>
    </xs:complexType>

    <xs:attribute name="NewAttribute" type="xs:string"></xs:attribute>

</xs:schema>

=== almerindo/TTAir_IMPL/conf/BehaviorConf04.xml
<?xml version="1.0" encoding="UTF-8"?> 
<Behavior xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="TTAirBehaviorSchema.xsd" Log="false" FilePathLog="./behavior.log">
  <Interaction ID="101" ClassName="org.ttair.proccess.impl.RecognizerHandInFrontIMPL">
    <Name>Hands together in front</Name>
    <Description>reconhece Maos à frente</Description>
  </Interaction>
  <Interaction ID="102" ClassName="org.ttair.proccess.impl.RecognizerFaceIMPL">
    <Name>Face de Usuário</Name>
    <Description>reconhece face do usuário</Description>
  </Interaction>
  <Interaction ID="103" ClassName="org.ttair.proccess.impl.RecognizerMousePositionIMPL">
    <Name>Mouse Position</Name>
    <Description>Reconhece Posicao do Mouse</Description>
  </Interaction>
  <Action ID="201" ClassName="org.ttair.action.impl.ActionImpl">
    <Name>ENVIAR IR POWER</Name>
  </Action>
  <Action ID="202" ClassName="org.ttair.action.impl.ActionImpl">
    <Name>SEND SIGN IR OK</Name>
  </Action>
  <Action ID="203" ClassName="org.ttair.action.impl.ActionImpl">
    <Name>SEND SIGN IR CH+</Name>
  </Action>
  <Action ID="204" ClassName="org.ttair.action.impl.ActionImpl">
    <Name>SEND SIGN IR CH-</Name>
  </Action>
  <BehaviorFrame ID="BF01">
    <Event ID="EVTBF01" RecognizerID="101" Cod="EVTHandInFront"/>
    <ActionID>201</ActionID>
    <ActionID>202</ActionID>
  </BehaviorFrame>
  <BehaviorFrame ID="BF02">
    <Event ID="EVTBF02" RecognizerID="102" Cod="EVTFaceRecognized"/>
    <ActionID>203</ActionID>
    <ActionID>204</ActionID>
  </BehaviorFrame>
  <BehaviorFrame ID="BF03">
    <Event ID="EVTBF03" RecognizerID="103" Cod="EVTMousePositionScreenLEFT_UP"/>
    <ActionID>201</ActionID>
    <ActionID>202</ActionID>
  </BehaviorFrame>
  <BehaviorFrame ID="BF04">
    <Event ID="EVTBF04" RecognizerID="103" Cod="EVTMousePositionScreenRIGHT_UP"/>
    <ActionID>203</ActionID>
    <ActionID>204</ActionID>
  </BehaviorFrame>
  <Expectancy ID="Exp01">
    <Name>Exp01</Name>
    <BehaviorframeID>BF01</BehaviorframeID>
  </Expectancy>
  <Expectancy ID="Exp02">
    <Name>Exp02</Name>
    <BehaviorframeID>BF02</BehaviorframeID>
  </Expectancy>
  <Expectancy ID="ExpFINAL">
    <Name>ExpFINAL</Name>
    <BehaviorframeID>BF03</BehaviorframeID>
    <BehaviorframeID>BF04</BehaviorframeID>
  </Expectancy>
  <BehaviorChain ID="BC001">
    <ExpectancyID>Exp01</ExpectancyID>
    <ExpectancyID>Exp02</ExpectancyID>
    <ExpectancyID>ExpFINAL</ExpectancyID>
    <ExpectancyTransition ID="ET0" Source="Exp01" Target="Exp02">
      <CausedBy>BF01</CausedBy>
    </ExpectancyTransition>
    <ExpectancyTransition ID="ET1" Source="Exp02" Target="ExpFINAL">
      <CausedBy>BF02</CausedBy>
    </ExpectancyTransition>
    <ExpectancyTransition ID="ET2" Source="ExpFINAL" Target="Exp01">
      <CausedBy>BF03</CausedBy>
    </ExpectancyTransition>
    <ExpectancyTransition ID="ET3" Source="ExpFINAL" Target="Exp02">
      <CausedBy>BF04</CausedBy>
    </ExpectancyTransition>
  </BehaviorChain>
</Behavior>

=== almerindo/TTAir_IMPL/conf/BehaviorConf.xml
<?xml version="1.0" encoding="UTF-8"?>
<Behavior xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="TTAirBehaviorSchema.xsd" ID="BH001" Log="true" FilePathLog="TTAirbehavior.log">
    <!-- > ########## Lista de Interações mapeadas ##########</-->
    <Interaction ID="INT01" ClassName="org.ttair.proccess.impl.RecognizerFaceIMPL">
        <Name>Hands together in front</Name>
    </Interaction>
    <Interaction ID="INT02" ClassName="org.ttair.proccess.impl.RecognizerHandInFrontIMPL">
        <Name>Hands left way</Name>
    </Interaction>
    <Interaction ID="INT03" ClassName="org.ttair.proccess.impl.RecognizerMousePositionIMPL">
        <Name>Hands right way</Name>
    </Interaction>
    <Interaction ID="INT04" ClassName="org.ttair.proccess.impl.RecognizerMousePositionIMPL">
        <Name>Mouse na esqueda</Name>
        <Description>EVT04 é recebido quando o mouse é colocado ao lado esquerdo da tela</Description>
    </Interaction>
    <Interaction ID="INT05" ClassName="org.ttair.proccess.impl.RecognizerMousePositionIMPL">
        <Name>Hands up way</Name>
    </Interaction>
    <Interaction ID="INT06" ClassName="org.ttair.proccess.impl.RecognizerMousePositionIMPL">
        <Name>Hands down way</Name>
    </Interaction>
    <Interaction ID="INT07" ClassName="org.ttair.proccess.impl.RecognizerMousePositionIMPL">
        <Name>Zoom hands together horizontally</Name>
    </Interaction>
    
    <!-- > ########## Lista de Ações mapeadas ##########</-->
    <Action ID="ACT01" ClassName="org.ttair.action.impl.ActionImpl">
        <Name>IR POWER</Name>
        <Description>Send sign IR Power</Description>
    </Action>
    <Action ID="ACT02" ClassName="org.ttair.action.impl.ActionImpl">
        <Name>IR OK</Name>
        <Description>Send sign IR OK</Description>
    </Action>
    <Action ID="ACT03" ClassName="org.ttair.action.impl.ActionImpl">
        <Name>IR CH+</Name>
        <Description>Send sign IR CH+</Description>
    </Action>
    <Action ID="ACT04" ClassName="org.ttair.action.impl.ActionImpl">
        <Name>IR CH-</Name>
        <Description>Send sign IR CH-</Description>
    </Action>
    <Action ID="ACT05" ClassName="org.ttair.action.impl.ActionImpl">
        <Name>IR VOL+</Name>
        <Description>Send sign IR VOL+</Description>
    </Action>
    <Action ID="ACT06" ClassName="org.ttair.action.impl.ActionImpl">
        <Name>IR VOL-</Name>
        <Description>Send sign IR VOL-</Description>
    </Action>
    <Action ID="ACT07" ClassName="org.ttair.action.impl.ActionImpl">
        <Name>IR EPG</Name>
        <Description>Send sign IR EPG - Eletronic Program Guide</Description>
    </Action>
    <Action ID="ACT08" ClassName="org.ttair.action.impl.ActionImpl">
        <Name>Show icon</Name>
        <Description>Show icon on screen</Description>
    </Action>
    
    <!-- > ########## Lista de Behavior frames mapeados ##########</-->
    <BehaviorFrame ID="BF01">
        <Name>BF01</Name>
        <Event ID="EVT01" RecognizerID="INT01" Cod="EVTFaceRecognized">
      		<Name>Face reconhecida</Name>
    	</Event>
        <ActionID>ACT01</ActionID>
        <ActionID>ACT08</ActionID>
    </BehaviorFrame>
    <BehaviorFrame ID="BF02">
        <Name>BF02</Name>
        <Event ID="EVT02" RecognizerID="INT02" Cod="EVTHandInFront">
      		<Name>Mãos para Frente</Name>
    	</Event>
        <ActionID>ACT03</ActionID>
        <ActionID>ACT08</ActionID>
    </BehaviorFrame>
    <BehaviorFrame ID="BF03">
        <Name>BF03</Name>
        <Event ID="EVT03" RecognizerID="INT03" Cod="EVTMousePositionScreenRIGHT_DOWN">
      		<Name>Direita Baixo</Name>
    	</Event>
        <ActionID>ACT04</ActionID>
        <ActionID>ACT08</ActionID>
    </BehaviorFrame>
    <BehaviorFrame ID="BF04">
        <Name>BF04</Name>
        <Event ID="EVT04" RecognizerID="INT05" Cod="EVTMousePositionScreenRIGHT_UP">
      		<Name>Direita CIMA</Name>
    	</Event>
        <ActionID>ACT05</ActionID>
        <ActionID>ACT08</ActionID>
    </BehaviorFrame>
    <BehaviorFrame ID="BF05">
        <Name>BF05</Name>
        <Event ID="EVT05" RecognizerID="INT06" Cod="EVTMousePositionScreenLEFT_UP">
      		<Name>Esquerda CIMA</Name>
    	</Event>
        <ActionID>ACT06</ActionID>
        <ActionID>ACT08</ActionID>
    </BehaviorFrame>
    <BehaviorFrame ID="BF06">
        <Name>BF06</Name>
         <Event ID="EVT06" RecognizerID="INT07" Cod="EVTMousePositionScreenLEFT_DOWN">
      		<Name>Esquerda CIMA</Name>
    	</Event>
        <ActionID>ACT07</ActionID>
        <ActionID>ACT08</ActionID>
    </BehaviorFrame>
    <BehaviorFrame ID="BF07">
        <Name>BF07</Name>
        <Event ID="EVT07" RecognizerID="INT04" Cod="EVTMousePositionScreenRIGHT_UP">
      		<Name>Direita CIMA</Name>
    	</Event>
        <ActionID>ACT02</ActionID>
        <ActionID>ACT08</ActionID>
    </BehaviorFrame>
    <BehaviorFrame ID="BF08">
        <Name>BF08</Name>
        <Event ID="EVT08" RecognizerID="INT05" Cod="EVTMousePositionScreenRIGHT_UP">
      		<Name>Direita CIMA</Name>
    	</Event>
        <ActionID>ACT03</ActionID>
        <ActionID>ACT08</ActionID>
    </BehaviorFrame>
    <BehaviorFrame ID="BF09">
        <Name>BF09</Name>
        <Event ID="EVT09" RecognizerID="INT06" Cod="EVTMousePositionScreenLEFT_UP">
      		<Name>Esquerda CIMA</Name>
    	</Event>
        <ActionID>ACT04</ActionID>
        <ActionID>ACT08</ActionID>
    </BehaviorFrame>
    
    <!-- > ########## Lista de Expectancies (Expectancy ou contexto)  mapeadas ##########</-->
    <Expectancy ID="exp01">
        <Name>OFF TV</Name>
        <Description>The TV is turned off</Description>
        <BehaviorframeID>BF01</BehaviorframeID>
    </Expectancy>
    <Expectancy ID="exp02">
        <Name>ON TV</Name>
        <Description>The TV is turned on</Description>
        <BehaviorframeID>BF01</BehaviorframeID>
        <BehaviorframeID>BF02</BehaviorframeID>
        <BehaviorframeID>BF03</BehaviorframeID>
        <BehaviorframeID>BF04</BehaviorframeID>
        <BehaviorframeID>BF05</BehaviorframeID>
        <BehaviorframeID>BF06</BehaviorframeID>
    </Expectancy>
    <Expectancy ID="exp03">
        <Name>EPG TV</Name>
        <Description>The TV is showing the EPG</Description>
        <BehaviorframeID>BF01</BehaviorframeID>
        <BehaviorframeID>BF06</BehaviorframeID>
        <BehaviorframeID>BF07</BehaviorframeID>
        <BehaviorframeID>BF08</BehaviorframeID>
        <BehaviorframeID>BF09</BehaviorframeID>
    </Expectancy>
    
    
        
    <!-- > ########## BEHAVIOR CHAIN ##########</-->
    <BehaviorChain ID="BC01">
        <Name>TV Remote Control</Name>
        <Description>Controlling the TV with manual Interactions</Description>
        <ExpectancyID>exp01</ExpectancyID>
        <ExpectancyID>exp02</ExpectancyID>
        <ExpectancyID>exp03</ExpectancyID>
        <!-- > ########## Lista de transições entre os contextos ou Expectancy(ies) ##########</-->
        <ExpectancyTransition ID="ET001" Source="exp01" Target="exp02">
         <CausedBy>BF01</CausedBy>
        </ExpectancyTransition>
        <ExpectancyTransition ID="ET002" Source="exp02" Target="exp01" >
         <CausedBy>BF01</CausedBy>
         </ExpectancyTransition>
        <ExpectancyTransition ID="ET003" Source="exp03" Target="exp01">
         <CausedBy>BF01</CausedBy>
        </ExpectancyTransition>
        <ExpectancyTransition ID="ET004" Source="exp02" Target="exp03">
         <CausedBy>BF06</CausedBy>
         </ExpectancyTransition>
        <ExpectancyTransition ID="ET005" Source="exp03" Target="exp02">
         <CausedBy>BF06</CausedBy>
         <CausedBy>BF07</CausedBy>
         </ExpectancyTransition>
    </BehaviorChain>
  
</Behavior>

=== almerindo/TTAir_IMPL/conf/BehaviorConf03.xml
<?xml version="1.0" encoding="UTF-8"?>
<Behavior xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="TTAirBehaviorSchema.xsd" ID="BH003" Log="true" FilePathLog="TTAirbehavior.log">
    <!-- > ########## Lista de Interações mapeadas ##########</-->
    <Interaction ID="INT01" ClassName="org.ttair.proccess.impl.RecognizerHandInFrontIMPL">
        <Name>Hands in Front</Name>
    </Interaction>
    <Interaction ID="INT02" ClassName="org.ttair.proccess.impl.RecognizerFaceIMPL">
        <Name>Face do usuário</Name>
    </Interaction>
    
    <Interaction ID="INT03" ClassName="org.ttair.proccess.impl.RecognizerMousePositionIMPL">
        <Name>Mouse Position LEFT_DOWN</Name>
    </Interaction>
    
    <!-- > ########## Lista de Ações mapeadas ##########</-->
    <Action ID="ACT01" ClassName="org.ttair.action.impl.ActionImpl">
        <Name>IR POWER</Name>
        <Description>Send sign IR Power</Description>
    </Action>
    <Action ID="ACT02" ClassName="org.ttair.action.impl.ActionImpl">
        <Name>IR OK</Name>
        <Description>Send sign IR OK</Description>
    </Action>
    <Action ID="ACT03" ClassName="org.ttair.action.impl.ActionImpl">
        <Name>IR CH+</Name>
        <Description>Send sign IR CH+</Description>
    </Action>
    <Action ID="ACT04" ClassName="org.ttair.action.impl.ActionImpl">
        <Name>IR CH-</Name>
        <Description>Send sign IR CH-</Description>
    </Action>
    
    
    <!-- > ########## Lista de Behavior frames mapeados ##########</-->
    <BehaviorFrame ID="BF01">
        <Name>BF01</Name>
        <Event ID="EVT01" RecognizerID="INT01" Cod="EVTHandInFront">
      		<Name>Mãos para Frente</Name>
    	</Event>
        <ActionID>ACT01</ActionID>
        <ActionID>ACT02</ActionID>
    </BehaviorFrame>
    <BehaviorFrame ID="BF02">
        <Name>BF02</Name>
        <Event ID="EVT02" RecognizerID="INT02" Cod="EVTFaceRecognized">
      		<Name>Face Reconhecida</Name>
    	</Event>
        <ActionID>ACT03</ActionID>
        <ActionID>ACT04</ActionID>
    </BehaviorFrame>
    <BehaviorFrame ID="BF03">
        <Name>BF03</Name>
        <Event ID="EVT03" RecognizerID="INT03" Cod="EVTMousePositionScreenLEFT_UP">
      		<Name>Mouse Esquerda para cima</Name>
    	</Event>
        <ActionID>ACT01</ActionID>
        <ActionID>ACT02</ActionID>
    </BehaviorFrame>
    <BehaviorFrame ID="BF04">
        <Name>BF04</Name>
        <Event ID="EVT04" RecognizerID="INT03" Cod="EVTMousePositionScreenRIGHT_UP">
      		<Name>Direita CIMA</Name>
    	</Event>
        <ActionID>ACT03</ActionID>
        <ActionID>ACT04</ActionID>
    </BehaviorFrame>
    
    
    <!-- > ########## Lista de Expectancies (Expectancy ou contexto)  mapeadas ##########</-->
    <Expectancy ID="exp01">
        <Name>OFF TV</Name>
        <Description>The TV is turned off</Description>
        <BehaviorframeID>BF01</BehaviorframeID>
    </Expectancy>
    <Expectancy ID="exp02">
        <Name>ON TV</Name>
        <Description>The TV is turned on</Description>
        <BehaviorframeID>BF01</BehaviorframeID>
        <BehaviorframeID>BF02</BehaviorframeID>
        <BehaviorframeID>BF03</BehaviorframeID>
        <BehaviorframeID>BF04</BehaviorframeID>
    </Expectancy>
    <Expectancy ID="exp03">
        <Name>EPG TV</Name>
        <Description>The TV is showing the EPG</Description>
        <BehaviorframeID>BF01</BehaviorframeID>
        <BehaviorframeID>BF02</BehaviorframeID>
    </Expectancy>
    <Expectancy ID="expFINAL">
        <Name>FIM</Name>
        <Description>FIM</Description>
    </Expectancy>
    
        
    <!-- > ########## BEHAVIOR CHAIN ##########</-->
    <BehaviorChain ID="BC01">
        <Name>TV Remote Control</Name>
        <Description>Controlling the TV with manual Interactions</Description>
        <ExpectancyID>exp01</ExpectancyID>
        <ExpectancyID>exp02</ExpectancyID>
        <ExpectancyID>exp03</ExpectancyID>
        <ExpectancyID>expFINAL</ExpectancyID>
        <!-- > ########## Lista de transições entre os contextos ou Expectancy(ies) ##########</-->
        <ExpectancyTransition ID="ET001" Source="exp01" Target="exp02">
         <CausedBy>BF01</CausedBy>
        </ExpectancyTransition>
        <ExpectancyTransition ID="ET002" Source="exp02" Target="exp01" >
         <CausedBy>BF01</CausedBy>
         </ExpectancyTransition>
        <ExpectancyTransition ID="ET003" Source="exp03" Target="exp01">
         <CausedBy>BF01</CausedBy>
        </ExpectancyTransition>
        <ExpectancyTransition ID="ET004" Source="exp02" Target="exp03">
         <CausedBy>BF04</CausedBy>
         </ExpectancyTransition>
        <ExpectancyTransition ID="ET005" Source="exp03" Target="exp02">
         <CausedBy>BF02</CausedBy>
         </ExpectancyTransition>
         <ExpectancyTransition ID="ET006" Source="exp03" Target="expFINAL">
         <CausedBy>BF01</CausedBy>
         </ExpectancyTransition>
    </BehaviorChain>
  
</Behavior>

=== almerindo/TTAir_IMPL/conf/BehaviorConf02.xml
<?xml version="1.0" encoding="UTF-8"?>
<Behavior xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="TTAirBehaviorSchema.xsd" ID="BH002" Log="false" FilePathLog="TTAirbehavior.log">
  <Interaction ID="INT01" ClassName="org.ttair.proccess.impl.RecognizerKinectHandPoint">
    <Name>AA01</Name>
    <Description>XX01</Description>
  </Interaction>
  <Interaction ID="INT02" ClassName="org.ttair.proccess.impl.RecognizerMousePositionIMPL">
    <Name>AA02</Name>
    <Description>XX02</Description>
  </Interaction>
  <Action ID="ACT01" ClassName="org.ttair.action.impl.ActionImpl">
    <Name>Acao ligar lampada</Name>
    <Description>ACT 01</Description>
  </Action>
  <Action ID="ACT02" ClassName="org.ttair.action.impl.ActionImpl">
    <Name>Acao ligar lampada</Name>
    <Description>ACT 02</Description>
  </Action>
  <BehaviorFrame ID="BF01">
    <Name>Behavior Frame 01</Name>
    <Event ID="EVT01" RecognizerID="INT01" Cod="EVTHandRightUP">
      <Name>Evento de mãos para cima</Name>
    </Event>
    <ActionID>ACT01</ActionID>
    <ActionID>ACT02</ActionID>
  </BehaviorFrame>
  <BehaviorFrame ID="BF02">
    <Name>Behavior Frame 02</Name>
    <Event ID="EVT02" RecognizerID="INT02" Cod="EVTMousePositionScreenRIGHT_DOWN">
      <Name>Evento de mãos para baixo</Name>
    </Event>
    <ActionID>ACT01</ActionID>
  </BehaviorFrame>
  <Expectancy ID="EXP01">
  	<Name>Expectancy 01</Name>
    <Description>Expectancy Nivel 01: Utilizada para iniciar a aplicação.</Description>
    <BehaviorframeID>BF01</BehaviorframeID>
  </Expectancy>
  <Expectancy ID="EXP02">
  	<Name> Expectancy 02</Name>
    <Description>Expectancy Nivel 02: Estado de expectativa após se iniciado o ambiente</Description>
    <BehaviorframeID>BF02</BehaviorframeID>
  </Expectancy>
  <BehaviorChain ID="BC001">
    <Name>Bc Tv</Name>
    <Description>Behavior Chain de TV</Description>
    <ExpectancyID>EXP01</ExpectancyID>
    <ExpectancyID>EXP02</ExpectancyID>
    <ExpectancyTransition ID="ETR01" Source="EXP01" Target="EXP02">
      <CausedBy>BF01</CausedBy>
    </ExpectancyTransition>
    <ExpectancyTransition ID="ETR02" Source="EXP02" Target="EXP01">
      <CausedBy>BF02</CausedBy>
    </ExpectancyTransition>
  </BehaviorChain>
</Behavior>

=== almerindo/TTAir_IMPL/conf/BehaviorTTAirHouse.xml
<?xml version="1.0" encoding="UTF-8"?>
<Behavior xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="TTAirBehaviorSchema.xsd" ID="BH004" Log="true" FilePathLog="TTAirbehavior.log">
  <Interaction ID="INT01" ClassName="org.ttair.proccess.impl.RecognizerMousePositionIMPL">
    <Name>INT01</Name>
    <Description>Interação que captura a posição do mouse na tela</Description>
  </Interaction>
 
  <Action ID="ACT03" ClassName="org.ttair.action.impl.ShowInconHouseC2">
    <Name>Seleciona Comodo 2</Name>
  </Action>
  <Action ID="ACT04" ClassName="org.ttair.action.impl.ShowInconHouseC3">
    <Name>Seleciona Comodo 3</Name>
  </Action>
  <Action ID="ACT05" ClassName="org.ttair.action.impl.ShowInconHouseC4">
    <Name>Seleciona Comodo 4</Name>
  </Action>
  <Action ID="ACT06" ClassName="org.ttair.action.impl.ShowInconHouseC5">
    <Name>Seleciona Comodo 5</Name>
  </Action>
  
  
  <BehaviorFrame ID="BF01">
    <Name>Behavior Frame 01</Name>
    <Event ID="EVT01" RecognizerID="INT01" Cod="EVTMousePositionScreenRIGHT_DOWN">
      <Name>Direita Baixo</Name>
    </Event>
    <ActionID>ACT06</ActionID>
  </BehaviorFrame>
  <BehaviorFrame ID="BF02">
    <Name>Behavior Frame 02</Name>
    <Event ID="EVT02" RecognizerID="INT01" Cod="EVTMousePositionScreenRIGHT_UP">
      <Name>Direita Cima</Name>
    </Event>
    <ActionID>ACT04</ActionID>
  </BehaviorFrame>
  <BehaviorFrame ID="BF03">
    <Name>Behavior Frame 03</Name>
    <Event ID="EVT03" RecognizerID="INT01" Cod="EVTMousePositionScreenLEFT_DOWN">
      <Name>Esquerda Baixo</Name>
    </Event>
    <ActionID>ACT05</ActionID>
  </BehaviorFrame>
  <BehaviorFrame ID="BF04">
    <Name>Behavior Frame 04</Name>
    <Event ID="EVT04" RecognizerID="INT01" Cod="EVTMousePositionScreenLEFT_UP">
      <Name>Esquerda Cima</Name>
    </Event>
    <ActionID>ACT03</ActionID>
  </BehaviorFrame>
  
  
  <Expectancy ID="EXP01">
  	<Name>Expectancy 01</Name>
    <Description>Expectancy Nivel 01: Utilizada para iniciar a aplicação.</Description>
    <BehaviorframeID>BF01</BehaviorframeID>
  </Expectancy>
  <Expectancy ID="EXP02">
  	<Name> Expectancy 02</Name>
    <Description>Expectancy Nivel 02: Estado de expectativa após se iniciado o ambiente</Description>
    <BehaviorframeID>BF02</BehaviorframeID>
  </Expectancy>
  <Expectancy ID="EXP03">
  	<Name> Expectancy 03</Name>
    <Description>EXP03 de teste</Description>
    <BehaviorframeID>BF03</BehaviorframeID>
  </Expectancy>
  <Expectancy ID="EXP04">
  	<Name> Expectancy 04</Name>
    <Description>EXP 04</Description>
    <BehaviorframeID>BF04</BehaviorframeID>
  </Expectancy>
  <BehaviorChain ID="BC001">
    <Name>Bc Tv</Name>
    <Description>Behavior Chain de TV</Description>
    <ExpectancyID>EXP01</ExpectancyID>
    <ExpectancyID>EXP02</ExpectancyID>
    <ExpectancyID>EXP03</ExpectancyID>
    <ExpectancyID>EXP04</ExpectancyID>
    <ExpectancyTransition ID="ETR01" Source="EXP01" Target="EXP02">
      <CausedBy>BF01</CausedBy>
    </ExpectancyTransition>
    <ExpectancyTransition ID="ETR02" Source="EXP02" Target="EXP03">
      <CausedBy>BF02</CausedBy>  
    </ExpectancyTransition>
    <ExpectancyTransition ID="ETR03" Source="EXP03" Target="EXP04">
      <CausedBy>BF03</CausedBy>  
    </ExpectancyTransition>
    <ExpectancyTransition ID="ETR04" Source="EXP04" Target="EXP01">
      <CausedBy>BF04</CausedBy>  
    </ExpectancyTransition>
  </BehaviorChain>
 
</Behavior>
